In [ ]:
import os
import sys
os.chdir(r"D:\tech\ADVT_python\vehicle_damage_detection")
PROJECT_PATH = os.getcwd()
if PROJECT_PATH not in sys.path:
    sys.path.append(PROJECT_PATH)
print(PROJECT_PATH)

D:\tech\ADVT_python\vehicle_damage_detection

In [2]:
# imports
from src.detector import DamageDetector
from src.assessment import DamageAssessment
from src.report import ReportGenerator
import pandas as pd

In [3]:
# load models
MODEL_PATH = "./models/best.pt"
detector = DamageDetector(MODEL_PATH)
assessment_engine = DamageAssessment()
report_generator = ReportGenerator()
print("Model Loaded Successfully.")

Model Loaded Successfully.

In [4]:
IMAGE_PATH = "./data/test/images/000040.jpg"
print(IMAGE_PATH)

./data/test/images/000040.jpg

In [5]:
# detection
annotated_image, detections = detector.detect(IMAGE_PATH)
print(f"Detected Damages : {len(detections)}")

Detected Damages : 1

In [6]:
#assessment
assessment = assessment_engine.assess(detections)
print("Assessment Completed.")

Assessment Completed.

In [7]:
PREDICTION_IMAGE = "./reports/figures/prediction.jpg"
detector.save_prediction(
    annotated_image,
    PREDICTION_IMAGE
)
print("Prediction image saved.")

Prediction image saved.

In [8]:
#  vehicle summary
summary = assessment["summary"]
print("VEHICLE SUMMARY")
for key, value in summary.items():
    print(f"{key.replace('_',' ').title():25}: {value}")

VEHICLE SUMMARY
Total Damages            : 1
Overall Severity         : Medium
Vehicle Health           : Fair
Risk Score               : 55
Inspection Status        : Needs Inspection

In [9]:
# damage table
damage_df = report_generator.to_dataframe(assessment)
damage_df["Confidence (%)"] = (
    damage_df["Confidence (%)"]
    .astype(float)
    .map(lambda x: f"{x:.1f}%")
)
display(damage_df)

,Damage Type,Confidence (%),Confidence Level,Severity,Location,Damage Size,Estimated Cost,Repair Priority,Recommendation
0,Scratch,53.0%,Low,Medium,Center Body,Medium,"₹2,000 - ₹6,000",Medium,Buffing and repainting recommended.

In [10]:
csv_path = report_generator.export_csv(
    assessment,
    filename="damage_report.csv"
)
print("CSV Saved Successfully")
print(csv_path)

CSV Saved Successfully
D:\tech\ADVT_python\vehicle_damage_detection\reports\csv\damage_report.csv

In [11]:
pdf_path = report_generator.export_pdf(
    assessment,
    filename="damage_report.pdf",
    prediction_image_path=PREDICTION_IMAGE
)
print("PDF Saved Successfully")
print(pdf_path)

PDF report generated successfully.
D:\tech\ADVT_python\vehicle_damage_detection\reports\pdf\damage_report.pdf
PDF Saved Successfully
D:\tech\ADVT_python\vehicle_damage_detection\reports\pdf\damage_report.pdf

In [12]:
#verifying saved files
from pathlib import Path

print("\nGenerated Files\n")

for folder in ["reports/csv", "reports/pdf", "reports/figures"]:
    print(f"\n{folder}")

    for file in sorted(Path(folder).glob("*")):
        print("   ", file.name)

Generated Files


reports/csv
    damage_report.csv
    results.csv

reports/pdf
    damage_report.pdf

reports/figures
    BoxF1_curve.png
    BoxP_curve.png
    BoxPR_curve.png
    BoxR_curve.png
    confusion_matrix.png
    confusion_matrix_normalized.png
    labels.jpg
    prediction.jpg
    results.png
    train_batch0.jpg
    train_batch1.jpg
    train_batch2.jpg
    train_batch3520.jpg
    train_batch3521.jpg
    train_batch3522.jpg
    val_batch0_labels.jpg
    val_batch0_pred.jpg
    val_batch1_labels.jpg
    val_batch1_pred.jpg
    val_batch2_labels.jpg
    val_batch2_pred.jpg

In [13]:
#completion
pd.read_csv(csv_path)

,Damage Type,Confidence (%),Confidence Level,Severity,Location,Damage Size,Estimated Cost,Repair Priority,Recommendation
0,Scratch,53.0,Low,Medium,Center Body,Medium,"₹2,000 - ₹6,000",Medium,Buffing and repainting recommended.

In [14]:
print("Vehicle Damage Detection Report Generated Successfully")
print(f"CSV Report        : {csv_path}")
print(f"PDF Report        : {pdf_path}")
print(f"Prediction Image  : {PREDICTION_IMAGE}")
print("\nProject Report Generation Completed.")

Vehicle Damage Detection Report Generated Successfully
CSV Report        : D:\tech\ADVT_python\vehicle_damage_detection\reports\csv\damage_report.csv
PDF Report        : D:\tech\ADVT_python\vehicle_damage_detection\reports\pdf\damage_report.pdf
Prediction Image  : ./reports/figures/prediction.jpg

Project Report Generation Completed.